//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaskedExtensionControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Signatures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Signatures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaskedExtensionControl.Properties.Signatures", typeof(Signatures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC  PIF SEA.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDB.
        /// </summary>
        internal static string _00_00_00_00 {
            get {
                return ResourceManager.GetString("00 00 00 00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ico.
        /// </summary>
        internal static string _00_00_01_00 {
            get {
                return ResourceManager.GetString("00 00 01 00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mpg mpeg.
        /// </summary>
        internal static string _00_00_01_B3 {
            get {
                return ResourceManager.GetString("00 00 01 B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mpg mpeg.
        /// </summary>
        internal static string _00_00_01_BA {
            get {
                return ResourceManager.GetString("00 00 01 BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _00_01_00_00 {
            get {
                return ResourceManager.GetString("00 01 00 00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBA.
        /// </summary>
        internal static string _00_01_42_44 {
            get {
                return ResourceManager.GetString("00 01 42 44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDA.
        /// </summary>
        internal static string _00_01_44_54 {
            get {
                return ResourceManager.GetString("00 01 44 54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wasm.
        /// </summary>
        internal static string _00_61_73_6d {
            get {
                return ResourceManager.GetString("00 61 73 6d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIF.
        /// </summary>
        internal static string _01 {
            get {
                return ResourceManager.GetString("01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEA.
        /// </summary>
        internal static string _02 {
            get {
                return ResourceManager.GetString("02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YTR.
        /// </summary>
        internal static string _03 {
            get {
                return ResourceManager.GetString("03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lz4.
        /// </summary>
        internal static string _04_22_4D_18 {
            get {
                return ResourceManager.GetString("04 22 4D 18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cwk.
        /// </summary>
        internal static string _05_07_00_00 {
            get {
                return ResourceManager.GetString("05 07 00 00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cwk.
        /// </summary>
        internal static string _06_07_E1_00 {
            get {
                return ResourceManager.GetString("06 07 E1 00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcapng.
        /// </summary>
        internal static string _0a_0d_0d_0a {
            get {
                return ResourceManager.GetString("0a 0d 0d 0a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mkv mka mks mk3d webm.
        /// </summary>
        internal static string _1A_45_DF_A3 {
            get {
                return ResourceManager.GetString("1A 45 DF A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to luac.
        /// </summary>
        internal static string _1B_4C_75_61 {
            get {
                return ResourceManager.GetString("1B 4C 75 61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gz tar.gz.
        /// </summary>
        internal static string _1F_8B {
            get {
                return ResourceManager.GetString("1F 8B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dat.
        /// </summary>
        internal static string _1F_8B_08_00 {
            get {
                return ResourceManager.GetString("1F 8B 08 00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z.
        /// </summary>
        internal static string _1F_9D {
            get {
                return ResourceManager.GetString("1F 9D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tar.z.
        /// </summary>
        internal static string _1F_9D1 {
            get {
                return ResourceManager.GetString("1F 9D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z.
        /// </summary>
        internal static string _1F_A0 {
            get {
                return ResourceManager.GetString("1F A0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tar.z.
        /// </summary>
        internal static string _1F_A01 {
            get {
                return ResourceManager.GetString("1F A01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fits fits.
        /// </summary>
        internal static string _20_20_20_20 {
            get {
                return ResourceManager.GetString("20 20 20 20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deb.
        /// </summary>
        internal static string _21_3C_61_72 {
            get {
                return ResourceManager.GetString("21 3C 61 72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wma wmv.
        /// </summary>
        internal static string _24_53_44_49 {
            get {
                return ResourceManager.GetString("24 53 44 49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ps.
        /// </summary>
        internal static string _25_21_50_53 {
            get {
                return ResourceManager.GetString("25 21 50 53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pdf.
        /// </summary>
        internal static string _25_50_44_46 {
            get {
                return ResourceManager.GetString("25 50 44 46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _27_05_19_56 {
            get {
                return ResourceManager.GetString("27 05 19 56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asf wmv.
        /// </summary>
        internal static string _30_26_B2_75 {
            get {
                return ResourceManager.GetString("30 26 B2 75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to der.
        /// </summary>
        internal static string _30_82 {
            get {
                return ResourceManager.GetString("30 82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7z.
        /// </summary>
        internal static string _37_7A_BC_AF {
            get {
                return ResourceManager.GetString("37 7A BC AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psd.
        /// </summary>
        internal static string _38_42_50_53 {
            get {
                return ResourceManager.GetString("38 42 50 53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string _3c_3f_78_6d {
            get {
                return ResourceManager.GetString("3c 3f 78 6d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fits.
        /// </summary>
        internal static string _3D_20_20_20 {
            get {
                return ResourceManager.GetString("3D 20 20 20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fh8.
        /// </summary>
        internal static string _41_47_44_33 {
            get {
                return ResourceManager.GetString("41 47 44 33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iff.
        /// </summary>
        internal static string _41_4E_49_4D {
            get {
                return ResourceManager.GetString("41 4E 49 4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to djvu djv.
        /// </summary>
        internal static string _41_54_26_54 {
            get {
                return ResourceManager.GetString("41 54 26 54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bac.
        /// </summary>
        internal static string _42_41_43_4B {
            get {
                return ResourceManager.GetString("42 41 43 4B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmp dib.
        /// </summary>
        internal static string _42_4D {
            get {
                return ResourceManager.GetString("42 4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bpg.
        /// </summary>
        internal static string _42_50_47_FB {
            get {
                return ResourceManager.GetString("42 50 47 FB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bz2.
        /// </summary>
        internal static string _42_5A_68 {
            get {
                return ResourceManager.GetString("42 5A 68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iso.
        /// </summary>
        internal static string _43_44_30_30 {
            get {
                return ResourceManager.GetString("43 44 30 30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cr2.
        /// </summary>
        internal static string _43_52 {
            get {
                return ResourceManager.GetString("43 52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swf.
        /// </summary>
        internal static string _43_57_53 {
            get {
                return ResourceManager.GetString("43 57 53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crx.
        /// </summary>
        internal static string _43_72_32_34 {
            get {
                return ResourceManager.GetString("43 72 32 34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _44_43_4D_01 {
            get {
                return ResourceManager.GetString("44 43 4D 01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dcm.
        /// </summary>
        internal static string _44_49_43_4D {
            get {
                return ResourceManager.GetString("44 49 43 4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bac.
        /// </summary>
        internal static string _44_49_53_4B {
            get {
                return ResourceManager.GetString("44 49 53 4B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ez3 iso.
        /// </summary>
        internal static string _45_4D_55_33 {
            get {
                return ResourceManager.GetString("45 4D 55 33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ez2.
        /// </summary>
        internal static string _45_4D_58_32 {
            get {
                return ResourceManager.GetString("45 4D 58 32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toast.
        /// </summary>
        internal static string _45_52_02_00 {
            get {
                return ResourceManager.GetString("45 52 02 00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flif.
        /// </summary>
        internal static string _46_4C_49_46 {
            get {
                return ResourceManager.GetString("46 4C 49 46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anim.
        /// </summary>
        internal static string _46_4F_52_4D____________ {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ??", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8svx 8sv svx snd iff.
        /// </summary>
        internal static string _46_4F_52_4D_____________38_53_56_58 {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 38 53 56 58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acbm.
        /// </summary>
        internal static string _46_4F_52_4D_____________41_43_42_4D {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 41 43 42 4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iff.
        /// </summary>
        internal static string _46_4F_52_4D_____________41_43_42_4D1 {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 41 43 42 4D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aiff snd aif.
        /// </summary>
        internal static string _46_4F_52_4D_____________41_49_46_46 {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 41 49 46 46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anbm.
        /// </summary>
        internal static string _46_4F_52_4D_____________41_4E_42_4D {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 41 4E 42 4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iff.
        /// </summary>
        internal static string _46_4F_52_4D_____________41_4E_42_4D1 {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 41 4E 42 4D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmus mus iff.
        /// </summary>
        internal static string _46_4F_52_4D_____________43_4D_55_53 {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 43 4D 55 53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iff.
        /// </summary>
        internal static string _46_4F_52_4D_____________46_41_4E_54 {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 46 41 4E 54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faxx fax iff.
        /// </summary>
        internal static string _46_4F_52_4D_____________46_41_58_58 {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 46 41 58 58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftxt.
        /// </summary>
        internal static string _46_4F_52_4D_____________46_54_58_54 {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 46 54 58 54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iff.
        /// </summary>
        internal static string _46_4F_52_4D_____________46_54_58_541 {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 46 54 58 541", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilbm.
        /// </summary>
        internal static string _46_4F_52_4D_____________49_4C_42_4D {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 49 4C 42 4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smus smu mus iff.
        /// </summary>
        internal static string _46_4F_52_4D_____________53_4D_55_53 {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 53 4D 55 53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yuvn yuv iff.
        /// </summary>
        internal static string _46_4F_52_4D_____________59_55_56_4E {
            get {
                return ResourceManager.GetString("46 4F 52 4D ?? ?? ?? ?? 59 55 56 4E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swf.
        /// </summary>
        internal static string _46_57_53 {
            get {
                return ResourceManager.GetString("46 57 53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ts tsa tsv.
        /// </summary>
        internal static string _47 {
            get {
                return ResourceManager.GetString("47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gif.
        /// </summary>
        internal static string _47_49_46_38 {
            get {
                return ResourceManager.GetString("47 49 46 38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gif.
        /// </summary>
        internal static string _47_49_46_38_39_61 {
            get {
                return ResourceManager.GetString("47 49 46 38 39 61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mpg mpeg.
        /// </summary>
        internal static string _471 {
            get {
                return ResourceManager.GetString("471", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp3.
        /// </summary>
        internal static string _49_44_33 {
            get {
                return ResourceManager.GetString("49 44 33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tif cr2.
        /// </summary>
        internal static string _49_49_2A_00 {
            get {
                return ResourceManager.GetString("49 49 2A 00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idx.
        /// </summary>
        internal static string _49_4E_44_58 {
            get {
                return ResourceManager.GetString("49 4E 44 58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vmdk.
        /// </summary>
        internal static string _4B_44_4D {
            get {
                return ResourceManager.GetString("4B 44 4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lz.
        /// </summary>
        internal static string _4C_5A_49_50 {
            get {
                return ResourceManager.GetString("4C 5A 49 50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLV.
        /// </summary>
        internal static string _4D_4C_56_49 {
            get {
                return ResourceManager.GetString("4D 4C 56 49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tiff.
        /// </summary>
        internal static string _4D_4D_00_2A {
            get {
                return ResourceManager.GetString("4D 4D 00 2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cab.
        /// </summary>
        internal static string _4D_53_43_46 {
            get {
                return ResourceManager.GetString("4D 53 43 46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mid midi.
        /// </summary>
        internal static string _4D_54_68_64 {
            get {
                return ResourceManager.GetString("4D 54 68 64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exe.
        /// </summary>
        internal static string _4D_5A {
            get {
                return ResourceManager.GetString("4D 5A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nes.
        /// </summary>
        internal static string _4E_45_53_1A {
            get {
                return ResourceManager.GetString("4E 45 53 1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orc.
        /// </summary>
        internal static string _4F_52_43 {
            get {
                return ResourceManager.GetString("4F 52 43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avro.
        /// </summary>
        internal static string _4F_62_6A_01 {
            get {
                return ResourceManager.GetString("4F 62 6A 01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ogg oga ogv.
        /// </summary>
        internal static string _4F_67_67_53 {
            get {
                return ResourceManager.GetString("4F 67 67 53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _50_41_52_31 {
            get {
                return ResourceManager.GetString("50 41 52 31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dat.
        /// </summary>
        internal static string _50_4D_4F_43 {
            get {
                return ResourceManager.GetString("50 4D 4F 43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avi wav webp.
        /// </summary>
        internal static string _52_49_46_46 {
            get {
                return ResourceManager.GetString("52 49 46 46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _52_4E_43_01 {
            get {
                return ResourceManager.GetString("52 4E 43 01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _52_4E_43_02 {
            get {
                return ResourceManager.GetString("52 4E 43 02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rar.
        /// </summary>
        internal static string _52_61_72_21 {
            get {
                return ResourceManager.GetString("52 61 72 21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dpx.
        /// </summary>
        internal static string _53_44_50_58 {
            get {
                return ResourceManager.GetString("53 44 50 58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rc.
        /// </summary>
        internal static string _53_45_51_36 {
            get {
                return ResourceManager.GetString("53 45 51 36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fits.
        /// </summary>
        internal static string _53_49_4D_50 {
            get {
                return ResourceManager.GetString("53 49 4D 50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bin.
        /// </summary>
        internal static string _53_50_30_31 {
            get {
                return ResourceManager.GetString("53 50 30 31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various.
        /// </summary>
        internal static string _53_5A_44_44 {
            get {
                return ResourceManager.GetString("53 5A 44 44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _54_41_50_45 {
            get {
                return ResourceManager.GetString("54 41 50 45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcv.
        /// </summary>
        internal static string _55_55_aa_aa {
            get {
                return ResourceManager.GetString("55 55 aa aa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dpx.
        /// </summary>
        internal static string _58_50_44_53 {
            get {
                return ResourceManager.GetString("58 50 44 53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lzfse.
        /// </summary>
        internal static string _62_76_78_32 {
            get {
                return ResourceManager.GetString("62 76 78 32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dex.
        /// </summary>
        internal static string _64_65_78_0A {
            get {
                return ResourceManager.GetString("64 65 78 0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p25 obt.
        /// </summary>
        internal static string _65_87_78_56 {
            get {
                return ResourceManager.GetString("65 87 78 56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flac.
        /// </summary>
        internal static string _66_4C_61_43 {
            get {
                return ResourceManager.GetString("66 4C 61 43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3gp 3g2.
        /// </summary>
        internal static string _66_74_79_70 {
            get {
                return ResourceManager.GetString("66 74 79 70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tox.
        /// </summary>
        internal static string _74_6F_78_33 {
            get {
                return ResourceManager.GetString("74 6F 78 33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tar.
        /// </summary>
        internal static string _75_73_74_61 {
            get {
                return ResourceManager.GetString("75 73 74 61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exr.
        /// </summary>
        internal static string _76_2F_31_01 {
            get {
                return ResourceManager.GetString("76 2F 31 01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to woff2.
        /// </summary>
        internal static string _77_4F_46_32 {
            get {
                return ResourceManager.GetString("77 4F 46 32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to woff.
        /// </summary>
        internal static string _77_4F_46_46 {
            get {
                return ResourceManager.GetString("77 4F 46 46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zlib.
        /// </summary>
        internal static string _78_01 {
            get {
                return ResourceManager.GetString("78 01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dmg.
        /// </summary>
        internal static string _78_01_73_0D {
            get {
                return ResourceManager.GetString("78 01 73 0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoCap Template.
        /// </summary>
        internal static string _78_56_34 {
            get {
                return ResourceManager.GetString("78 56 34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xar.
        /// </summary>
        internal static string _78_61_72_21 {
            get {
                return ResourceManager.GetString("78 61 72 21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zlib.
        /// </summary>
        internal static string _78_9C {
            get {
                return ResourceManager.GetString("78 9C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zlib.
        /// </summary>
        internal static string _78_DA {
            get {
                return ResourceManager.GetString("78 DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtf.
        /// </summary>
        internal static string _7B_5C_72_74 {
            get {
                return ResourceManager.GetString("7B 5C 72 74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _7F_45_4C_46 {
            get {
                return ResourceManager.GetString("7F 45 4C 46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cin.
        /// </summary>
        internal static string _80_2A_5F_D7 {
            get {
                return ResourceManager.GetString("80 2A 5F D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png.
        /// </summary>
        internal static string _89_50_4E_47 {
            get {
                return ResourceManager.GetString("89 50 4E 47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toast.
        /// </summary>
        internal static string _8B_45_52_02 {
            get {
                return ResourceManager.GetString("8B 45 52 02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcap.
        /// </summary>
        internal static string a1_b2_c3_d4 {
            get {
                return ResourceManager.GetString("a1 b2 c3 d4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wma wmv.
        /// </summary>
        internal static string A6_D9_00_AA {
            get {
                return ResourceManager.GetString("A6 D9 00 AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBA.
        /// </summary>
        internal static string BE_BA_FE_CA {
            get {
                return ResourceManager.GetString("BE BA FE CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string CA_FE_BA_BE {
            get {
                return ResourceManager.GetString("CA FE BA BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CE_FA_ED_FE {
            get {
                return ResourceManager.GetString("CE FA ED FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lep.
        /// </summary>
        internal static string cf_84_01 {
            get {
                return ResourceManager.GetString("cf 84 01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CF_FA_ED_FE {
            get {
                return ResourceManager.GetString("CF FA ED FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcap.
        /// </summary>
        internal static string d4_c3_b2_a1 {
            get {
                return ResourceManager.GetString("d4 c3 b2 a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rpm.
        /// </summary>
        internal static string ed_ab_ee_db {
            get {
                return ResourceManager.GetString("ed ab ee db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EF_BB_BF {
            get {
                return ResourceManager.GetString("EF BB BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xz tar.xz.
        /// </summary>
        internal static string FD_37_7A_58 {
            get {
                return ResourceManager.GetString("FD 37 7A 58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FE_ED_FA_CE {
            get {
                return ResourceManager.GetString("FE ED FA CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FE_ED_FA_CF {
            get {
                return ResourceManager.GetString("FE ED FA CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jpg.
        /// </summary>
        internal static string FF_D8_FF_DB {
            get {
                return ResourceManager.GetString("FF D8 FF DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jpeg.
        /// </summary>
        internal static string FF_D8_FF_E0 {
            get {
                return ResourceManager.GetString("FF D8 FF E0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp3.
        /// </summary>
        internal static string FF_FB {
            get {
                return ResourceManager.GetString("FF FB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FF_FE {
            get {
                return ResourceManager.GetString("FF FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FF_FE_00_00 {
            get {
                return ResourceManager.GetString("FF FE 00 00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
    }
}
